# Generated by Django 5.0.6 on 2024-06-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountnumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardnumber',
            new_name='card_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='accounttype',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cardtype',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='api.account')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='api.account')),
            ],
        ),
    ]
