# Generated by Django 5.0.6 on 2024-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_accountnumber_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(max_length=3, unique=True),
        ),
    ]
