# Generated by Django 5.0.6 on 2024-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_account_account_number_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
