# Generated by Django 5.0.6 on 2024-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_user_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(unique=True),
        ),
    ]
