# Generated by Django 5.0.6 on 2024-06-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_card_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='account',
        ),
    ]
