# Generated by Django 5.0.6 on 2024-06-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_user_card_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.account'),
        ),
    ]
