# Generated by Django 5.0.6 on 2024-06-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
